language: java
jdk:
- oraclejdk9
services:
- postgresql
before_script:
- export TZ=Europe/Moscow
- psql -U postgres -f database/init.sql
script: "./gradlew clean build"
branches:
  only:
  - develop
deploy:
  provider: heroku
  api_key:
    secure: 382bcbe0-a0e3-4ab1-94f9-e11580c80127
  app: rsoi
  on:
      branch: develop
